### ISSUE TITLE
Blocklist not working on Blocked Players (Crops)

### ISSUE THREAD

**Issue by spval** [Ottermandias/Accountant#22]

**Comment by Ottermandias** [comment]
Works fine for me. This only blocks the characters apartment and private chambers. 
What's the issue?

**Comment by spval** [comment]
Oh, okay, the name is a bit misleading then. I thought it would block crops that you don't want showing up in the list, and not apartment/chambers.

**Comment by Ottermandias** [comment]
Ah, you thought it would block all crops tended to by a player, instead of all crops belonging to a player?
Yeah, I can see that. Though everything in this list blocks specific items from appearing in your list (not even from being recorded, just from appearing)

**Comment by spval** [comment]
Not all crops, just specific ones from appearing. From seeing how the other filters worked I figured 'Player' was just a stand in.

**Comment by spval** [comment]
For example, on a plot I keep Curiel Root constantly planted. So in Blocked Players (Crops) I figured I could enter Curiel Root in there and it would prevent it from showing in the list.

**Comment by Ottermandias** [comment]
The way this is saved is that if you're tending a crop in an apartment or chamber, it gets assigned to the tending player. Since you can't do anything with pots in other players apartments or chambers, this is a unique correspondence.
For all other crops I can read out the current server, zone, ward and plot (whether indoors or outdoors), so I can assign those to the specific plot.
That's the 'Player' / 'Plot' distinction.  (Indoor pots also get their pot position to keep them distinct)

**Comment by Ottermandias** [comment]
Ahh, no, I haven't included a per-plant block.
But if you just want to not have grown out crops that you keep alive in the list, you can just delete those specifically in Delete Entries. Since you're not tending, harvesting or planting them after growing out, they will not be re-added.

**Comment by Ottermandias** [comment]
Added an per-plant block.
